sudo: required
dist: trusty
services:
- docker
language: go
go:
- 1.9
os:
- linux
- osx
env:
  matrix:
  - TARGETS="check"
  - TARGETS="testsuite"
  - TARGETS="beater-test"
  global:
  - GOX_FLAGS="-arch amd64"
addons:
  apt:
    packages:
    - python-virtualenv
before_install:
- mkdir -p $HOME/gopath/src/github.com/aristanetworks/openconfigbeat
- rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/aristanetworks/openconfigbeat
- export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/aristanetworks/openconfigbeat
- cd $HOME/gopath/src/github.com/aristanetworks/openconfigbeat
- go get -v github.com/elastic/beats/vendor/github.com/pierrre/gotestcover
- go get -v github.com/Masterminds/glide
install:
- true
script:
- make $TARGETS
